spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/lkdcode
    username: lkdcode
    password: lkdcode

  flyway:
    enabled: true
    default-schema: public
    schemas: public
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/lkdcode
    user: lkdcode
    password: lkdcode
    locations:
      - classpath:db/migration

  sql:
    init:
      mode: always