version: "3.9"

name: lkdcode-container
services:
  redis:
    image: redis:7-alpine
    container_name: lkdcode-tx-redis
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "lkdcode" ]
    ports:
      - "16379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata: