jwt:
  access-token:
    secret-key: 0821248f10d83256506fcf20c1fb1aafffb11436b4acd47ac243b5e207aa4390e2d6be8a5325eb3925b7fb7c9ddc7875f1f50447da6b23e72af1c70a45449cf6
    expired: 900
    issuer: lkdcode

  refresh-token:
    secret-key: cb3af1a39224f401465e75f85acb8753022584c4e61c874835022c686e4f522db5d1c94850ceed6a824439916da7bd7ba5201dd8795a9b97a6d5630287a971cf
    expired: 1_296_000
    issuer: lkdcode