server:
  port: 18080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/lkdcode-tx
    username: lkdcode
    password: lkdcode

  data:
    mongodb:
      host: localhost
      port: 17017
      username: lkdcode
      password: lkdcode
      database: lkdcode-tx
      authentication-database: admin

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    io.r2dbc.postgresql: DEBUG
    io.r2dbc.pool: DEBUG
    org.mongodb.driver.connection: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver.protocol: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%-25.25t] %-40.40logger{39} : %m%n"