spring:
  application:
    name: spring-webflux-transaction-0

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    io.r2dbc.h2: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.transaction: DEBUG